"""Bivariate PMF for correlated combo props using Gaussian copula.

Motivation
----------
When building combo-prop PMFs (pts+ast, pts+reb, etc.), the independence
assumption of discrete convolution is wrong.  In WNBA data:

- pts & ast are *negatively* correlated within a game (high-scoring = shot-first
  offense; playmaking nights = fewer personal shot attempts)
- pts & reb are modestly positively correlated (active nights, more possessions)
- reb & ast are approximately independent

PenaltyBlog's Bivariate Poisson soccer model captures this by fitting a shared
covariance parameter.  The WNBA translation uses a Gaussian copula, which:

1. Is distribution-agnostic (works with NegBinom/Poisson marginals)
2. Has a single parameter ρ per pair (easy to estimate from data)
3. Produces a correct joint PMF P(X + Y > line) without Monte Carlo

Method
------
Given marginal PMFs P(X = j) and P(Y = k) with correlation ρ:

1. Compute CDFs F_X(j) and F_Y(k)
2. Convert to normal scores: u_j = F_X(j), v_k = F_Y(k)
3. Apply Gaussian copula: P(X=j, Y=k) ∝ P(X=j) * P(Y=k) * exp(copula_term)
   where copula_term adjusts the joint probability for correlation
4. Renormalize the joint matrix
5. Sum over {j,k : j+k > line} for over-probability

The copula density adjustment for Gaussian copula C_ρ(u,v) uses:
    c(u,v) = (1/sqrt(1-ρ²)) * exp(-(ρ²(φ_u² + φ_v²) - 2ρ*φ_u*φ_v) / (2(1-ρ²)))
where φ_u = Φ⁻¹(u), φ_v = Φ⁻¹(v), Φ⁻¹ is the normal quantile function.

Usage
-----
    from wnba_props_model.models.bivariate_pmf import (
        estimate_correlations,
        build_bivariate_pmf,
        bivariate_prob_over,
    )

    # Fit correlations from historical data once per season
    corr_map = estimate_correlations(features_wide_df)
    # {"pts_ast": -0.15, "pts_reb": 0.08, "reb_ast": -0.05, ...}

    # At inference time
    pts_pmf = np.array([...])   # marginal PMF for pts
    ast_pmf = np.array([...])   # marginal PMF for ast
    joint   = build_bivariate_pmf(pts_pmf, ast_pmf, rho=corr_map["pts_ast"])
    p_over  = bivariate_prob_over(joint, line=20.5)  # P(pts + ast > 20.5)
"""
from __future__ import annotations

import logging
from typing import Iterable

import numpy as np
from scipy import stats

logger = logging.getLogger(__name__)

# Default correlations — theory-grounded estimates replacing inflated OOF artefact values.
# See artifacts/models/stage4_baseline/combo_correlations_by_pos.json for the position-
# stratified version loaded at runtime (gitignored; regenerated by weekly_calibration).
_DEFAULT_CORRELATIONS: dict[str, float] = {
    "pts_ast":     -0.12,  # pts and ast negatively correlated (ball-dominant guards)
    "pts_reb":      0.08,  # modest positive (active offensive nights)
    "reb_ast":     -0.05,  # approximately independent
    "pts_reb_ast": -0.08,  # composite: dominated by pts-ast term
    "stocks":       0.12,  # stl + blk: both defensive activity
    "blk_stl":      0.12,  # alias key used by position-stratified path
}

# Position-stratified fallback used when combo_correlations_by_pos.json is absent.
_DEFAULT_CORRELATIONS_BY_POS: dict[str, dict[str, float]] = {
    "all": {"pts_ast": -0.12, "pts_reb": 0.08, "reb_ast": -0.05, "pts_reb_ast": -0.08, "stocks": 0.12, "blk_stl": 0.12},
    "G":   {"pts_ast": -0.18, "pts_reb": 0.02, "reb_ast": -0.08, "pts_reb_ast": -0.10, "stocks": 0.08, "blk_stl": 0.10},
    "F":   {"pts_ast": -0.10, "pts_reb": 0.10, "reb_ast":  0.02, "pts_reb_ast": -0.06, "stocks": 0.12, "blk_stl": 0.14},
    "C":   {"pts_ast": -0.02, "pts_reb": 0.18, "reb_ast": -0.10, "pts_reb_ast": -0.04, "stocks": 0.15, "blk_stl": 0.16},
}

# Minimum samples required to estimate a reliable correlation
_MIN_SAMPLES_FOR_CORR = 100

# Hard clamp on ρ to keep copula numerically stable
_MAX_ABS_RHO = 0.85


def _safe_norm_ppf(u: np.ndarray, eps: float = 1e-6) -> np.ndarray:
    """Normal quantile function with clipped input to avoid ±∞."""
    return stats.norm.ppf(np.clip(u, eps, 1.0 - eps))


def estimate_correlations(
    features_wide: "pd.DataFrame",
    pairs: Iterable[tuple[str, str]] | None = None,
    min_samples: int = _MIN_SAMPLES_FOR_CORR,
    position_col: str | None = None,
) -> "dict[str, float] | dict[str, dict[str, float]]":
    """Estimate empirical Pearson correlations between stat pairs from wide table.

    Parameters
    ----------
    features_wide: wide feature DataFrame with actual_{stat} columns
    pairs:         stat pairs to estimate; defaults to canonical combo pairs
    min_samples:   minimum non-NaN rows to trust the estimate

    Returns
    -------
    When ``position_col`` is None: dict mapping combo key → ρ.
    When ``position_col`` is provided: dict {"G": {...}, "F": {...}, "C": {...}, "all": {...}}.
    Missing pairs fall back to _DEFAULT_CORRELATIONS.
    """
    import pandas as pd

    if pairs is None:
        pairs = [
            ("pts", "ast"),
            ("pts", "reb"),
            ("reb", "ast"),
            ("stl", "blk"),
        ]

    def _compute_corr_map(df: "pd.DataFrame") -> dict[str, float]:
        corr_map = dict(_DEFAULT_CORRELATIONS)
        for s1, s2 in pairs:
            c1, c2 = f"actual_{s1}", f"actual_{s2}"
            if c1 not in df.columns or c2 not in df.columns:
                continue
            valid = df[[c1, c2]].dropna()
            if len(valid) < min_samples:
                continue
            rho = float(np.corrcoef(valid[c1].values, valid[c2].values)[0, 1])
            rho = float(np.clip(rho, -_MAX_ABS_RHO, _MAX_ABS_RHO))
            key = f"{s1}_{s2}" if (s1, s2) in [("pts", "ast"), ("pts", "reb"), ("reb", "ast")] else f"{s2}_{s1}"
            corr_map[key] = round(rho, 4)
            logger.debug("[bivariate_pmf] Estimated ρ(%s, %s) = %.4f from %d samples", s1, s2, rho, len(valid))
        return corr_map

    # P3.5: position-stratified correlations
    if position_col is not None and position_col in features_wide.columns:
        result: dict[str, dict[str, float]] = {"all": _compute_corr_map(features_wide)}
        def _primary(pos: str) -> str:
            if not isinstance(pos, str) or not pos:
                return "F"
            c = pos.strip()[0].upper()
            return c if c in ("G", "F", "C") else "F"
        primary_pos = features_wide[position_col].map(_primary)
        for bucket in ("G", "F", "C"):
            subset = features_wide[primary_pos == bucket]
            result[bucket] = _compute_corr_map(subset)
        return result

    return _compute_corr_map(features_wide)


def fit_joint_to_marginals(
    seed_joint: np.ndarray,
    target_x: np.ndarray,
    target_y: np.ndarray,
    tolerance: float = 1e-10,
    max_iterations: int = 10_000,
    epsilon: float = 1e-15,
) -> tuple[np.ndarray, dict]:
    """Sinkhorn/IPF iterations to make joint PMF exactly match target marginals.

    Iteratively scales rows then columns so that::

        joint.sum(axis=1) == target_x   (within ``tolerance``)
        joint.sum(axis=0) == target_y   (within ``tolerance``)

    This guarantees E[X + Y] = E[X] + E[Y] up to floating-point precision when
    the combo PMF is derived from anti-diagonal sums of the fitted joint.

    Parameters
    ----------
    seed_joint : 2D array (nx, ny) — initial joint (e.g. from Gaussian copula)
    target_x   : 1D array (nx,) — target row marginal (will be renormalized)
    target_y   : 1D array (ny,) — target col marginal (will be renormalized)
    tolerance  : convergence threshold on max(row_err, col_err)
    max_iterations : hard cap on Sinkhorn iterations
    epsilon    : small floor to avoid division by zero

    Returns
    -------
    (joint, diagnostics)
    joint       : 2D array with exact marginals
    diagnostics : dict with keys converged, iterations,
                  row_marginal_max_error, col_marginal_max_error
    """
    joint = np.asarray(seed_joint, dtype=float).copy()
    target_x = np.asarray(target_x, dtype=float)
    target_y = np.asarray(target_y, dtype=float)

    sx = target_x.sum()
    sy = target_y.sum()
    if sx <= 0 or sy <= 0:
        return joint, {
            "converged": False, "iterations": 0,
            "row_marginal_max_error": float("inf"),
            "col_marginal_max_error": float("inf"),
        }
    target_x = target_x / sx
    target_y = target_y / sy

    positive_x = target_x > 0
    positive_y = target_y > 0

    # Ensure positive seed mass wherever both marginals are positive
    joint = np.where(
        positive_x[:, None] & positive_y[None, :],
        np.maximum(joint, epsilon),
        0.0,
    )
    if joint.sum() <= 0:
        joint = np.outer(target_x, target_y)
    joint /= joint.sum()

    iteration = 0
    for iteration in range(1, max_iterations + 1):
        row_sums = joint.sum(axis=1)
        row_scale = np.where(
            positive_x & (row_sums > 0),
            target_x / np.maximum(row_sums, epsilon),
            0.0,
        )
        joint *= row_scale[:, None]

        col_sums = joint.sum(axis=0)
        col_scale = np.where(
            positive_y & (col_sums > 0),
            target_y / np.maximum(col_sums, epsilon),
            0.0,
        )
        joint *= col_scale[None, :]

        row_err = float(np.max(np.abs(joint.sum(axis=1) - target_x)))
        col_err = float(np.max(np.abs(joint.sum(axis=0) - target_y)))
        if max(row_err, col_err) <= tolerance:
            break

    total = joint.sum()
    if total > 0:
        joint /= total

    final_row_err = float(np.max(np.abs(joint.sum(axis=1) - target_x)))
    final_col_err = float(np.max(np.abs(joint.sum(axis=0) - target_y)))
    diagnostics = {
        "converged": max(final_row_err, final_col_err) <= tolerance * 10,
        "iterations": iteration,
        "row_marginal_max_error": final_row_err,
        "col_marginal_max_error": final_col_err,
    }
    return joint, diagnostics


def _achieved_correlation(
    joint: np.ndarray,
    pmf_x: np.ndarray,
    pmf_y: np.ndarray,
) -> float:
    """Compute the count-level Pearson correlation implied by a joint PMF matrix."""
    ks_x = np.arange(joint.shape[0], dtype=float)
    ks_y = np.arange(joint.shape[1], dtype=float)
    mx = float(ks_x @ pmf_x)
    my = float(ks_y @ pmf_y)
    vx = float(((ks_x - mx) ** 2) @ pmf_x)
    vy = float(((ks_y - my) ** 2) @ pmf_y)
    if vx < 1e-14 or vy < 1e-14:
        return 0.0
    cov = float(np.sum(joint * (ks_x[:, None] - mx) * (ks_y[None, :] - my)))
    return float(cov / np.sqrt(vx * vy))


def build_bivariate_pmf(
    pmf_x: np.ndarray,
    pmf_y: np.ndarray,
    rho: float,
) -> np.ndarray:
    """Build joint PMF P(X=j, Y=k) using Gaussian copula + IPF marginal correction.

    Parameters
    ----------
    pmf_x: marginal PMF for X (array of probabilities summing to ~1)
    pmf_y: marginal PMF for Y (array of probabilities summing to ~1)
    rho:   Pearson correlation target for the bivariate distribution

    Returns
    -------
    2D array of shape (len(pmf_x), len(pmf_y)) representing the joint PMF.
    Row sums equal pmf_x and column sums equal pmf_y exactly (within 1e-9).

    Notes
    -----
    When |ρ| < 0.02, the joint PMF is the outer product (independence).
    Otherwise a Gaussian copula seed is used, then Sinkhorn/IPF iterations
    enforce exact marginal matching — guaranteeing E[X+Y] = E[X] + E[Y].
    """
    pmf_x = np.asarray(pmf_x, dtype=float)
    pmf_y = np.asarray(pmf_y, dtype=float)

    # Normalize marginals
    if pmf_x.sum() < 1e-9 or pmf_y.sum() < 1e-9:
        return np.outer(pmf_x, pmf_y)
    pmf_x = pmf_x / pmf_x.sum()
    pmf_y = pmf_y / pmf_y.sum()

    # Independence case: outer product already satisfies marginals exactly
    rho = float(np.clip(rho, -_MAX_ABS_RHO, _MAX_ABS_RHO))
    if abs(rho) < 0.02:
        return np.outer(pmf_x, pmf_y)

    nx, ny = len(pmf_x), len(pmf_y)

    # CDFs: F_X(j) = P(X ≤ j), F_Y(k) = P(Y ≤ k)
    # Use midpoint CDF for discrete atoms (avoids boundary issues)
    cdf_x = np.cumsum(pmf_x)
    cdf_y = np.cumsum(pmf_y)
    cdf_x_prev = np.concatenate([[0.0], cdf_x[:-1]])
    cdf_y_prev = np.concatenate([[0.0], cdf_y[:-1]])
    u = 0.5 * (cdf_x + cdf_x_prev)
    v = 0.5 * (cdf_y + cdf_y_prev)

    # Normal scores
    phi_u = _safe_norm_ppf(u)
    phi_v = _safe_norm_ppf(v)

    # Gaussian copula log-density:
    # log c(u,v;ρ) = -0.5*log(1-ρ²) - (ρ²*(φ_u²+φ_v²) - 2ρ*φ_u*φ_v) / (2*(1-ρ²))
    r2 = rho ** 2
    denom = 2.0 * (1.0 - r2)
    phi_u_sq = phi_u[:, None] ** 2
    phi_v_sq = phi_v[None, :] ** 2
    cross = phi_u[:, None] * phi_v[None, :]
    log_copula = -0.5 * np.log(1.0 - r2) - (r2 * (phi_u_sq + phi_v_sq) - 2.0 * rho * cross) / denom
    log_copula = np.clip(log_copula, -10.0, 10.0)

    # Copula seed joint: outer product weighted by copula density
    seed = np.outer(pmf_x, pmf_y) * np.exp(log_copula)
    seed = np.clip(seed, 0.0, None)

    if seed.sum() < 1e-12:
        return np.outer(pmf_x, pmf_y)

    # IPF: enforce exact marginals on the copula seed
    joint, _ipf_diag = fit_joint_to_marginals(seed, pmf_x, pmf_y)
    return joint


def bivariate_prob_over(
    joint_pmf: np.ndarray,
    line: float,
) -> float:
    """Compute P(X + Y > line) from a joint PMF matrix.

    Parameters
    ----------
    joint_pmf: 2D array P(X=j, Y=k) of shape (nx, ny)
    line:      threshold (e.g. 20.5)

    Returns
    -------
    float in [0, 1]: P(X + Y > line)
    """
    joint_pmf = np.asarray(joint_pmf, dtype=float)
    nx, ny = joint_pmf.shape
    total = 0.0
    for j in range(nx):
        for k in range(ny):
            if j + k > line:
                total += joint_pmf[j, k]
    return float(np.clip(total, 0.0, 1.0))


def adjust_combo_pmf_for_correlation(
    pmf_x: np.ndarray,
    pmf_y: np.ndarray,
    stat_x: str,
    stat_y: str,
    corr_map: dict[str, float] | None = None,
    position: str | None = None,
    corr_map_by_pos: "dict[str, dict[str, float]] | None" = None,
) -> tuple[np.ndarray, dict]:
    """Build a correlation-adjusted sum PMF P(X + Y = k) with IPF marginal preservation.

    The joint PMF is built via Gaussian copula then corrected with Sinkhorn/IPF
    iterations so that joint.sum(axis=1) == pmf_x and joint.sum(axis=0) == pmf_y
    exactly. This guarantees E[X+Y] = E[X]+E[Y] up to floating-point precision.

    Parameters
    ----------
    pmf_x, pmf_y : marginal PMFs
    stat_x, stat_y : stat names (used to look up ρ from corr_map)
    corr_map : flat dict of canonical pair key → ρ; defaults to _DEFAULT_CORRELATIONS
    position : P3.5 — primary position bucket ("G"/"F"/"C") for stratified lookup
    corr_map_by_pos : P3.5 — {"G": {...}, "F": {...}, "C": {...}, "all": {...}}

    Returns
    -------
    (sum_pmf, diagnostics)
    sum_pmf     : 1D array, PMF of X + Y, length = len(pmf_x) + len(pmf_y) - 1
    diagnostics : dict with:
        requested_latent_rho       : float — the ρ used for the copula
        achieved_count_correlation : float — Pearson correlation in the fitted joint
        row_marginal_max_error     : float — max |joint.sum(axis=1) - pmf_x|
        col_marginal_max_error     : float — max |joint.sum(axis=0) - pmf_y|
        combo_mean_error           : float — |E[X+Y] - (E[X]+E[Y])|
        ipf_iterations             : int
        ipf_converged              : bool
    """
    # P3.5: resolve the correlation map to use
    if corr_map_by_pos is not None:
        _primary = position.strip()[0].upper() if (isinstance(position, str) and position) else None
        if _primary in corr_map_by_pos:
            corr_map = corr_map_by_pos[_primary]
        else:
            corr_map = corr_map_by_pos.get("all", _DEFAULT_CORRELATIONS)

    if corr_map is None:
        corr_map = _DEFAULT_CORRELATIONS

    key1 = f"{stat_x}_{stat_y}"
    key2 = f"{stat_y}_{stat_x}"
    rho  = corr_map.get(key1, corr_map.get(key2, 0.0))

    pmf_x = np.asarray(pmf_x, dtype=float)
    pmf_y = np.asarray(pmf_y, dtype=float)
    if pmf_x.sum() > 1e-9:
        pmf_x = pmf_x / pmf_x.sum()
    if pmf_y.sum() > 1e-9:
        pmf_y = pmf_y / pmf_y.sum()

    # Build copula seed, then apply IPF for exact marginal preservation
    rho_clipped = float(np.clip(rho, -_MAX_ABS_RHO, _MAX_ABS_RHO))
    if abs(rho_clipped) < 0.02:
        # Independence: outer product already has exact marginals; no IPF needed
        joint = np.outer(pmf_x, pmf_y)
        ipf_diag: dict = {
            "converged": True, "iterations": 0,
            "row_marginal_max_error": 0.0, "col_marginal_max_error": 0.0,
        }
    else:
        # build_bivariate_pmf already applies IPF internally
        nx, ny = len(pmf_x), len(pmf_y)
        cdf_x = np.cumsum(pmf_x)
        cdf_y = np.cumsum(pmf_y)
        cdf_x_prev = np.concatenate([[0.0], cdf_x[:-1]])
        cdf_y_prev = np.concatenate([[0.0], cdf_y[:-1]])
        u = 0.5 * (cdf_x + cdf_x_prev)
        v = 0.5 * (cdf_y + cdf_y_prev)
        phi_u = _safe_norm_ppf(u)
        phi_v = _safe_norm_ppf(v)
        r2 = rho_clipped ** 2
        denom = 2.0 * (1.0 - r2)
        log_copula = (
            -0.5 * np.log(1.0 - r2)
            - (r2 * (phi_u[:, None] ** 2 + phi_v[None, :] ** 2) - 2.0 * rho_clipped * phi_u[:, None] * phi_v[None, :])
            / denom
        )
        log_copula = np.clip(log_copula, -10.0, 10.0)
        seed = np.outer(pmf_x, pmf_y) * np.exp(log_copula)
        seed = np.clip(seed, 0.0, None)
        if seed.sum() < 1e-12:
            seed = np.outer(pmf_x, pmf_y)
        joint, ipf_diag = fit_joint_to_marginals(seed, pmf_x, pmf_y)

    # Extract combo PMF via anti-diagonal sums P(X+Y=k)
    nx, ny = joint.shape
    max_k = nx + ny - 2
    sum_pmf = np.zeros(max_k + 1, dtype=float)
    for j in range(nx):
        for k in range(ny):
            sum_pmf[j + k] += joint[j, k]
    if sum_pmf.sum() > 1e-9:
        sum_pmf /= sum_pmf.sum()

    # Compute diagnostics
    ks_x = np.arange(len(pmf_x))
    ks_y = np.arange(len(pmf_y))
    ks_c = np.arange(len(sum_pmf))
    mean_x = float(ks_x @ pmf_x) if pmf_x.sum() > 0 else 0.0
    mean_y = float(ks_y @ pmf_y) if pmf_y.sum() > 0 else 0.0
    combo_mean = float(ks_c @ sum_pmf) if sum_pmf.sum() > 0 else 0.0
    combo_mean_error = abs(combo_mean - (mean_x + mean_y))

    diagnostics = {
        "requested_latent_rho":       rho,
        "achieved_count_correlation": _achieved_correlation(joint, pmf_x, pmf_y),
        "row_marginal_max_error":     ipf_diag["row_marginal_max_error"],
        "col_marginal_max_error":     ipf_diag["col_marginal_max_error"],
        "combo_mean_error":           combo_mean_error,
        "ipf_iterations":             ipf_diag["iterations"],
        "ipf_converged":              ipf_diag["converged"],
    }
    return sum_pmf, diagnostics
