"""Surrogate feature-subset ablation (DEVELOPMENT-ONLY EXPLORATION).

Classification: SURROGATE feature-subset ablation. This runner does NOT invoke the signed
champion's OOF / PMF / calibration / delivery pipeline. It trains a fixed surrogate model
(HistGradientBoostingRegressor Poisson conditional mean -> NB count PMF with method-of-
moments dispersion, identical per candidate so differences isolate the FEATURES) and scores
full-count NLL / RPS out-of-fold on expanding chronological DEVELOPMENT folds only.

IMPORTANT SCOPE LIMITS (read before citing any result):
  * This is DEVELOPMENT-ONLY. No final holdout is scored here. A tail of dates is RESERVED
    and excluded from every fold so a later, separate PR can run a genuine one-shot holdout;
    those reserved dates are never evaluated in this runner.
  * Conditional-on-played: rows are filtered to games the player actually played
    (did_play == True, else actual_minutes > 0). Results are therefore conditional on play,
    not full-delivery (which would include DNP / minutes uncertainty).
  * This is NOT proof, certification, or promotion evidence. The result is not
    promotion-eligible. It cannot be used to certify a market edge.

Selection metric priority: full-count NLL (primary), then RPS. AUC/accuracy are not used.

Outputs (all generated by THIS runner):
  artifacts/feature_ablation/ablation_verdict.json
  artifacts/feature_ablation/ABLATION_VERDICT.md
  artifacts/feature_ablation/RUN_MANIFEST.json
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
import platform
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import typer

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from wnba_props_model.evaluation.diagnostics import pmf_nll, rps  # noqa: E402

app = typer.Typer(add_completion=False)
PROPS = ["pts", "reb", "ast", "fg3m", "stl", "blk", "turnover"]
SEED = 0  # surrogate model random_state; chronological folds are otherwise deterministic
CLASSIFICATION = "surrogate feature-subset ablation"
PROTOCOL = "development-only expanding chronological folds; no holdout scored"
_ID = {"game_id", "player_id", "team_id", "opponent_team_id", "game_date", "season",
       "player_name", "team_abbreviation", "opponent_team_abbreviation", "home_away"}


def _sha256_file(path: str | Path) -> str | None:
    p = Path(path)
    if not p.exists():
        return None
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _source_commit() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=str(Path(__file__).parent.parent),
            stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return "unknown"


def _nb_pmf(mu: float, size: float, ms: int) -> np.ndarray:
    from scipy.special import gammaln
    mu = max(float(mu), 1e-3); size = max(float(size), 1e-3)
    k = np.arange(ms); p = size / (size + mu)
    lp = gammaln(k + size) - gammaln(size) - gammaln(k + 1) + size * np.log(p) + k * np.log1p(-p)
    out = np.exp(lp); s = out.sum()
    return out / s if s > 0 else np.ones(ms) / ms


def _score_candidate(df, prop, cols, folds, ms):
    """Mean OOS NLL + RPS across DEVELOPMENT folds for one candidate feature set."""
    from sklearn.ensemble import HistGradientBoostingRegressor
    target = f"actual_{prop}"
    if target not in df.columns:
        return None
    use = [c for c in cols if c in df.columns and c not in _ID and c != target]
    if len(use) < 4:
        return None
    nlls, rpss, n = [], [], 0
    fold_rows = []
    for tr_end, va_end in folds:
        tr = df[df["game_date"] < tr_end]
        va = df[(df["game_date"] >= tr_end) & (df["game_date"] < va_end)]
        tr = tr[tr[target].notna()]; va = va[va[target].notna()]
        if len(tr) < 400 or len(va) < 80:
            fold_rows.append({"train": int(len(tr)), "valid": int(len(va)), "used": False})
            continue
        Xtr = tr[use].astype(float).fillna(0.0).values
        ytr = np.clip(tr[target].astype(float).values, 0, None)
        m = HistGradientBoostingRegressor(loss="poisson", max_iter=250, learning_rate=0.05,
                                          max_depth=3, random_state=SEED).fit(Xtr, ytr)
        mu_tr = np.clip(m.predict(Xtr), 1e-3, None)
        v = ((ytr - mu_tr) ** 2).mean(); mbar = mu_tr.mean()
        size = max(mbar ** 2 / max(v - mbar, 1e-3), 0.5)   # MoM NB dispersion (train only)
        mu_va = np.clip(m.predict(va[use].astype(float).fillna(0.0).values), 1e-3, None)
        for mu, y in zip(mu_va, va[target].astype(int).values):
            pmf = _nb_pmf(mu, size, ms)
            nlls.append(pmf_nll(pmf, int(y))); rpss.append(rps(pmf, int(y)))
        n += len(va)
        fold_rows.append({"train": int(len(tr)), "valid": int(len(va)), "used": True})
    if not nlls:
        return None
    # Feature-set hash isolates exactly which columns this candidate used.
    feat_hash = _sha256_text(json.dumps(sorted(use)))
    return {"nll": float(np.mean(nlls)), "rps": float(np.mean(rpss)), "n": n,
            "n_features": len(use), "feature_set_sha256": feat_hash, "folds": fold_rows}


def _render_markdown(verdict: dict) -> str:
    lines = [
        "# Per-Prop Feature Ablation (Development-Only, Surrogate)",
        "",
        f"- Classification: **{verdict['classification']}**",
        f"- Protocol: {verdict['protocol']}",
        f"- Conditional-on-played (DNP excluded): **{verdict['dnp_excluded']}**",
        f"- Reserved (unscored) tail dates: **{verdict['reserved_tail_dates']}**",
        f"- Surrogate: HGB Poisson mean -> NB PMF (MoM dispersion); random_state={verdict['seed']}",
        f"- Metric: full-count NLL (primary), RPS (tie-break). AUC/accuracy not used.",
        "",
        "> This is development-only exploration. It is NOT proof, certification, or promotion",
        "> evidence and is NOT promotion-eligible.",
        "",
        "| Prop | Winner | G0 NLL | Winner NLL | Delta vs G0 | Improves G0? |",
        "|---|---|--:|--:|--:|---|",
    ]
    for prop in PROPS:
        r = verdict["results"].get(prop, {})
        if r.get("status") == "no_result":
            lines.append(f"| {prop} | (no result) | - | - | - | - |")
            continue
        lines.append(
            f"| {prop} | {r['winner']} | {r['g0_nll']:.4f} | {r['winner_nll']:.4f} | "
            f"{r['nll_delta_vs_g0']:+.4f} | {r['improves_over_g0']} |")
    lines += [
        "",
        "## Conclusion",
        "",
        verdict["conclusion"],
        "",
    ]
    return "\n".join(lines) + "\n"


@app.command()
def main(features: str = typer.Option("data/processed/wnba_player_game_features_wide.parquet"),
         maps: str = typer.Option("config/feature_ablation_maps_v1.json"),
         out_dir: str = typer.Option("artifacts/feature_ablation"),
         reserved_tail_dates: int = typer.Option(
             25, "--reserved-tail-dates", "--holdout-dates",
             help="Tail dates EXCLUDED from every fold and NOT scored (reserved for a future "
                  "genuine one-shot holdout in a separate PR). Never evaluated here.")) -> None:
    features_sha = _sha256_file(features)
    maps_sha = _sha256_file(maps)
    df = pd.read_parquet(features)
    df["game_date"] = pd.to_datetime(df["game_date"])
    n_rows_raw = int(len(df))
    dnp_excluded = False
    if "did_play" in df.columns:
        df = df[df["did_play"] == True]  # noqa: E712
        dnp_excluded = True
    elif "actual_minutes" in df.columns:
        df = df[df["actual_minutes"].fillna(0) > 0]
        dnp_excluded = True
    cand_maps = json.loads(Path(maps).read_text())["candidates"]

    dates = np.sort(df["game_date"].unique())
    dev = dates[:-reserved_tail_dates] if reserved_tail_dates > 0 else dates
    cuts = [dev[int(len(dev) * f)] for f in (0.55, 0.7, 0.85)]
    folds = [(cuts[i], cuts[i + 1] if i + 1 < len(cuts) else dev[-1] + np.timedelta64(1, "D"))
             for i in range(len(cuts))]
    fold_dates = [{"train_end": str(pd.Timestamp(a).date()),
                   "valid_end": str(pd.Timestamp(b).date())} for a, b in folds]

    results: dict = {}
    feature_map_hashes: dict = {}
    for prop in PROPS:
        ms = int(df[f"actual_{prop}"].max()) + 8 if f"actual_{prop}" in df.columns else 60
        res = {}
        for cand, pm in cand_maps.items():
            cols = pm.get(prop, [])
            r = _score_candidate(df, prop, cols, folds, ms)
            if r:
                res[cand] = r
                feature_map_hashes[f"{cand}/{prop}"] = r["feature_set_sha256"]
        if not res or "G0" not in res:
            results[prop] = {"status": "no_result"}
            continue
        best = min(res, key=lambda c: (res[c]["nll"], res[c]["rps"]))
        g0 = res["G0"]
        results[prop] = {
            "winner": best, "n_features_winner": res[best]["n_features"],
            "g0_nll": round(g0["nll"], 4), "winner_nll": round(res[best]["nll"], 4),
            "nll_delta_vs_g0": round(res[best]["nll"] - g0["nll"], 4),
            "g0_rps": round(g0["rps"], 4), "winner_rps": round(res[best]["rps"], 4),
            "rps_delta_vs_g0": round(res[best]["rps"] - g0["rps"], 4),
            "improves_over_g0": bool(res[best]["nll"] < g0["nll"] - 1e-4),
            "all": {c: {"nll": round(r["nll"], 4), "rps": round(r["rps"], 4),
                        "n": r["n"], "n_features": r["n_features"]}
                    for c, r in res.items()},
        }
        typer.echo(f"[{prop}] winner={best} NLL {g0['nll']:.4f}->{res[best]['nll']:.4f} "
                   f"({res[best]['nll'] - g0['nll']:+.4f}) improves={results[prop]['improves_over_g0']}")

    any_improves = any(r.get("improves_over_g0") for r in results.values())
    conclusion = (
        "None of the tested feature subsets improved the tested surrogate model under the "
        "specified development-only protocol. New tracking data is a high-priority next source "
        "of information, but this experiment does not prove it is the only possible source of "
        "improvement." if not any_improves else
        "At least one tested feature subset improved the tested surrogate model under the "
        "development-only protocol; this is exploratory and requires a genuine holdout + the "
        "signed champion pipeline before any promotion claim."
    )

    verdict = {
        "schema_version": 1,
        "classification": CLASSIFICATION,
        "protocol": PROTOCOL,
        "promotion_eligible": False,
        "seed": SEED,
        "dnp_excluded": dnp_excluded,
        "conditional_on": "played (did_play/actual_minutes > 0)",
        "reserved_tail_dates": int(reserved_tail_dates),
        "fold_dates": fold_dates,
        "props": PROPS,
        "results": results,
        "conclusion": conclusion,
    }

    out = Path(out_dir); out.mkdir(parents=True, exist_ok=True)
    (out / "ablation_verdict.json").write_text(json.dumps(verdict, indent=2, default=str))
    (out / "ABLATION_VERDICT.md").write_text(_render_markdown(verdict))

    manifest = {
        "schema_version": 1,
        "classification": CLASSIFICATION,
        "protocol": PROTOCOL,
        "promotion_eligible": False,
        "generated_by": "scripts/run_prop_ablation.py",
        "source_commit": _source_commit(),
        "created_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        "seed": SEED,
        "dnp_excluded": dnp_excluded,
        "conditional_on": "played (did_play/actual_minutes > 0)",
        "inputs": {
            "features_path": features,
            "features_sha256": features_sha,
            "features_rows_raw": n_rows_raw,
            "features_rows_after_dnp_filter": int(len(df)),
            "features_n_columns": int(df.shape[1]),
            "maps_path": maps,
            "maps_sha256": maps_sha,
        },
        "fold_dates": fold_dates,
        "reserved_tail_dates": int(reserved_tail_dates),
        "feature_map_hashes": feature_map_hashes,
        "package_versions": {
            "python": platform.python_version(),
            "numpy": np.__version__,
            "pandas": pd.__version__,
            "scipy": __import__("scipy").__version__,
            "scikit_learn": __import__("sklearn").__version__,
        },
        "outputs": {
            "ablation_verdict.json": _sha256_file(out / "ablation_verdict.json"),
            "ABLATION_VERDICT.md": _sha256_file(out / "ABLATION_VERDICT.md"),
        },
    }
    (out / "RUN_MANIFEST.json").write_text(json.dumps(manifest, indent=2, default=str))
    typer.echo(f"\n[ablation] {CLASSIFICATION} -> {out}/ (verdict + markdown + manifest)")


if __name__ == "__main__":
    app()
